# Chapter 1 Linear Algebra
## 1.2 Elements of Linear Algebra

### 1.2.1.1 Linear Combinations
From the slides:
"
A linear combination in linear algebra is a new vector constructed from a
subset by multiplying each vector by a constant and adding the results. A
linear subspace is a result of linear combination.
Definition 1.2.1 (Linear subspace) A linear subspace of V is a subset U ⊆ V
that is closed under vector addition and scalar multiplication. That is, for all
u1, u2 ∈ U and
α ∈ R, it holds that
> u1 + u2 ∈ U, and
α u1 ∈ U. 
"
#### Example 1
The vector y = (1.11, 2.22, 3.33) can be written as a linear combination of the unit vectors (0,0,1), (0,1,0) and (1,0,0):


In [14]:
import numpy as np
x = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
y = ([3.33, 2.22, 1.11])
scalars = np.linalg.solve(x, y)
scalars

array([1.11, 2.22, 3.33])

#### Example 2
The vector y = (1.23, 4.56, 7.89) can be written as a linear combination of the unit vectors (0,1,1), (1,1,0) and (1,0,1): 

In [15]:
x = np.array([[0, 1, 1],
              [1, 1, 0],
              [1, 0, 1]])
y = ([7.89, 4.56, 1.23])
scalars = np.linalg.solve(x, y)
scalars

array([-1.05,  5.61,  2.28])

### 1.2.2 Orthogonality

### 1.2.2.1 Orthonormal Bases

#### Example
Getting the Orthogonal Vector of two vectors [[2, -4, 5]] and [[4, 10, 2]]



In [16]:
# declare the two vectors
v1 = [[2, -4, 5]]
v2 = [[4, 10, 2]]

# get the transpose of v1
v1_transpose = np.transpose(v1)

# matrix multiply v2 and v1_transpose
ortho_vector = np.dot(v2, v1_transpose)

ortho_vector


array([[-22]])

### 1.2.4 Eigenvalues and Eigenvectors

#### Example 
Getting the eigenvalues and eigenvectors of an array  

In [17]:
# inital dec of the array
array1 = np.array([[2, 3], [4, 1]]) 

# get the eigenvalues and eigenvectors from numpy
w, v = np.linalg.eig(array1)

# print results
print(w)
print(v)

[ 5. -2.]
[[ 0.70710678 -0.6       ]
 [ 0.70710678  0.8       ]]
